### ISSUE TITLE
error: pathspec 'gistup' did not match any file(s) known to git

### ISSUE THREAD

**Issue by nswitanek** [mbostock/gistup#22]
Hi,

I've followed the "Let's Make a Block" tutorial and gotten stuck trying to run gistup. I've pasted the error below, which isn't addressed in your gistup troubleshooting section. It seems possibly a git configuration issue rather than a gistup issue, but not one I've been able to resolve. Could you provide a suggestion?

Thank you.

```
c:\Users\username\AppData\Roaming\npm\node_modules\gistup\lib\gistup\unless.js:11
    throw error;
          ^
Error: Command failed: error: pathspec 'gistup' did not match any file(s) known to git.
error: pathspec 'commit.'' did not match any file(s) known to git.

    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
```

**Comment by mbostock** [comment]
This is almost certainly a Windows issue, and I’m afraid I won’t be much help at solving it. My guess from the cryptic error is that it’s failing inside the `gitCommit` function:

```js
function gitCommit(callback) {
  child.exec("git commit --allow-empty -m 'Initial gistup commit.'", function(error, stdout, stderr) {
    if (!error && stderr) process.stderr.write(stderr), error = new Error("git commit failed.");
    if (!error && stdout) process.stdout.write(stdout);
    callback(error);
  });
}
```

Specifically, it looks like your shell is not correctly parsing the single-quoted commit message (`Initial gistup commit.`) and is instead passing `gistup` and `commit.'` as separate arguments to `git`. Which of course fails.

It’s possible that gistup could be modified to support Windows, but my guess is that this would require substantial changes. So you might be out of luck. Sorry. :frowning:

**Comment by nswitanek** [comment]
Understood. Thanks very much for your swift reply.

**Comment by CrandellWS** [comment]
I can bypass the mentioned error https://github.com/mbostock/gistup/issues/22#issue-90510743 using underscores like so

    function gitCommit(callback) {
      child.exec("git commit --allow-empty -m 'Initial_gistup_commit'", function(error, stdout, stderr) {
        if (!error && stderr) process.stderr.write(stderr), error = new Error("git commit failed.");
        if (!error && stdout) process.stdout.write(stdout);
        callback(error);
      });
    }

Though, a new error occurs:

    Initialized empty Git repository in C:/apps/demo/htdocs/github/gists/test1/.git/
    [master (root-commit) b04b2a3] 'Initial_gistup_commit.'
    C:\npm\node_modules\gistup\lib\gistup\unless.js:11
        throw error;
        ^

    Error: invalid gist id: undefined
        at C:\npm\node_modules\gistup\bin\gistup:169:67
        at IncomingMessage.<anonymous> (C:\npm\node_modules\gistup\lib\gistup\api.js:28:7)
        at emitNone (events.js:72:20)
        at IncomingMessage.emit (events.js:166:7)
        at endReadableNT (_stream_readable.js:893:12)
        at doNTCallback2 (node.js:429:9)
        at process._tickCallback (node.js:343:17)

**Comment by CrandellWS** [comment]
oh I think the new error in https://github.com/mbostock/gistup/issues/22#issuecomment-143469666  is because of a bad user token. will check just need to figure out where the old one got stored....

**Comment by CrandellWS** [comment]
ok so the storage was in %USERPROFILE% and it did work.

**Comment by CrandellWS** [comment]
Ok **it is creating the Gist on GitHub** using https://github.com/mbostock/gistup/tree/c6f3b193de8a99f6275496ec2dd6761b57c3e598 but I only have access to a public key and get stuck with the following error: 

    Initialized empty Git repository in C:/github/gists/gistup/.git/
    [master (root-commit) 1ccc3b9] 'Initial_gistup_commit'
    gist xXxXxXxXxXxXxXxXxXxX created!
    https://gist.github.com/xXxXxXxXxXxXxXxXxXxX
    C:\npm\node_modules\gistup\lib\gistup\unless.js:11
        throw error;
        ^

    Error: Command failed: C:\Windows\system32\cmd.exe /s /c "git push -fu 'origin' master"
    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

        at ChildProcess.exithandler (child_process.js:203:12)
        at emitTwo (events.js:87:13)
        at ChildProcess.emit (events.js:172:7)
        at maybeClose (internal/child_process.js:817:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

with which has the **Gist ID** (xXxXxXxXxXxXxXxXxXxX) which is enough information to clone the repo using Git, from which it is off to the tracks... 

Using my pull request https://github.com/mbostock/gistup/pull/25 Here is the process that works on a Windows system in a bash shell:

1. replace xXxXxXxXxXxXxXxXxXxX with your Gist id (see above error for example)
2. replace yourUserName

    ~$ mkdir myGist
    ~$ cd myGist
    ~$ gistup
    ~$ rm -rf .git
    ~$ git clone https://gist.github.com/yourUserName/xXxXxXxXxXxXxXxXxXxX
    ~$ echo 'word' > file
    ~$ git add -A
    ~$ git commit -m 'Commit Message is Required'
    ~$ git push origin



From there most should know what to do.

**Comment by CrandellWS** [comment]
ok so a note to myself https://github.com/CrandellWS/gistup/commit/6e765a4a27e88920b1fc50d14ba7177ba8491258

**Comment by CrandellWS** [comment]
Looking at https://www.npmjs.com/package/npm-execspawn in consideration of cross platform exec calls

**Comment by CrandellWS** [comment]
Got this much figured out 

    function gitTestWin(callback) {
      var env = process.env,
        varName,
        envCopy = {};
        // Copy process.env into envCopy
        for (varName in env) {
          envCopy[varName] = env[varName];
        }
        envCopy['wtf'] = 'It is a win thing';
        child.exec("echo %wtf%", { env: envCopy}, function(error, stdout, stderr) {
        if (!error && stderr) process.stderr.write(stderr), error = new Error("It has failed.");
        if (!error && stdout) process.stdout.write(stdout);
        if(error){
          console.warn(error.message);
        }
        console.warn('EXIT');
        process.exit(1);
      });
    }

**Comment by CrandellWS** [comment]
Cross platform??>

  var env = process.env,
    varName,
    envArgv,
    envCopy = {};
    // Copy process.env into envCopy
    for (varName in env) {
      envCopy[varName] = env[varName];
    }
    envCopy['wtf'] = 'It is a win thing';
    
    if(process.platform === "win32") {
      envArgv = "%wtf%";
    } else {
      envArgv = "$wtf";
    }
    child.exec("echo " + envArgv, { env: envCopy}, function(error, stdout, stderr) {

**Comment by CrandellWS** [comment]
Here is what I have got so far https://github.com/CrandellWS/gistup/commit/6114d26d98d70968176975b094f2af86d5e4973c 

Though it looks like more can still be done.

**Comment by CrandellWS** [comment]
With Windows this fails

  function gitCommit(callback) {
    child.exec('git commit --allow-empty -m "Initial gistup commit"',function(error, stdout, stderr) {
        if (!error && stderr) process.stderr.write(stderr), error = new Error("git commit failed.");
        if (!error && stdout) process.stdout.write(stdout);
        callback(error);
    });
  }
  
vs this works

  function gitCommit(callback) {
    child.exec("git commit --allow-empty -m 'Initial gistup commit.'", function(error, stdout, stderr) {
      if (!error && stderr) process.stderr.write(stderr), error = new Error("git commit failed.");
      if (!error && stdout) process.stdout.write(stdout);
      callback(error);
    });
  }

do not have current access to linux but it is assumed that there is reason to not just change it like mentioned

**Comment by CrandellWS** [comment]
bit stuck on Right single quotation mark (U+2019) vs. Apostrophe (U+0027) not sure what to do

**Comment by CrandellWS** [comment]
deferred to 
    child.exec('git config --get remote.' + crossPlatform.envVal('remoteName') + '.url || '+ crossPlatform.rEcho(),{ env: crossPlatform.newEnvVal('remoteName', argv.remote)}, function(error, stdout, stderr) {

**Comment by CrandellWS** [comment]
now you can see the rEcho (returned echo) in cross-platform.js https://github.com/CrandellWS/gistup/commit/010814e68d97f9515c3870eafc417111ca295fed

Can Someone test this on a linux system for me

**Comment by CrandellWS** [comment]
Windows users will hopefully find success using:
    npm install  -g gistup-npc

**Comment by CrandellWS** [comment]
The previous package was renamed to **mkg** so use **`npm install -g mkg`** to install. 

Was able to get Ubuntu up and running to test the package and found it is now successfully working. 

A side note for Ubuntu users getting **npm** running was not so straight forward. For my purposes the **Best Solution To get npm working correctly on Ubuntu**:

  1. Option 2 @ [https://docs.npmjs.com/getting-started/fixing-npm-permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npm-s-default-directory-to-another-directory)
  2. Create soft link to nodejs for node in *~/bin*  -> **```ln -s `which nodejs` ~/bin/node```** !important

**Comment by gilsedition** [comment]
This issue is fixed with the solution **CrandellWS** provided. Thanks @CrandellWS
