### ISSUE TITLE
Git Bash on Windows 10 - TypeError: process.stdin.setRawMode is not a function

### ISSUE THREAD

**Issue by micahstubbs** [mbostock/gistup#32]
Would be nice to support [Git Bash](https://git-scm.com/download/win) on Windows

```
$ gistup -m "WebVR Experiment"
Welcome to GISTUP!

Since this is your first time using gistup, we need to create a
GitHub personal access token to grant gistup permission to create
gists on your behalf. You’ll only have to do this once, and you
can easily revoke this token in the future if desired.

When you press any key to continue, your web browser will open.
Please login (if needed) and fill out the resulting form to create
an access token. When you’re done, copy the access token to the
clipboard and paste it back into the terminal.

Press any key to open GitHub… C:\Users\m\AppData\Roaming\npm\node_modules\gistup\lib\gistup\get-settings.js:37
      process.stdin.setRawMode(true);
                    ^

TypeError: process.stdin.setRawMode is not a function
    at ReadFileContext.callback (C:\Users\m\AppData\Roaming\npm\node_modules\gistup\lib\gistup\get-settings.js:37:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)

```

**Comment by mbostock** [comment]
I am not going to support Windows due to my focus on other projects, but if someone else wants to contribute support for Windows, I will review the pull request.
