### ISSUE TITLE
gistup will not upload file

### ISSUE THREAD

**Issue by glw** [mbostock/gistup#36]
the .gistup.json file is in my home directory with correct api key. I set it up with rights to gist.

Here is the error message I get:

```
$ gistup test_v1.yaml 
```

```
Initialized empty Git repository in /home/garret/projects/webmap/server/tangram_styles/.git/
[master (root-commit) 48671ed] Initial gistup commit.
 1 file changed, 5597 insertions(+)
 create mode 100644 fpdcc_v1.yaml
gist 2162c96304134b437f79ef4d7f9a644a created!
https://gist.github.com/2162c96304134b437f79ef4d7f9a644a
/home/garret/.nvm/versions/node/v7.7.3/lib/node_modules/gistup/lib/gistup/unless.js:11
    throw error;
    ^

Error: Command failed: git push -fu 'origin' master
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.exithandler (child_process.js:210:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

Any thoughts on what might be wrong?

**Comment by mbostock** [comment]
In addition to the API key, you’ll need to be able to use `git` to push to GitHub. Try GitHub’s guide here:

https://help.github.com/articles/connecting-to-github-with-ssh/

**Comment by glw** [comment]
that did it! Thank you!
